Implement Quotes Board (#1029)
* feat(cool-messages): add configuration files

* feat(cool-messages): add primary logic

* feat(cool-message): forward messages instead of using embed

For this feature, the version of JDA had to be bumped to 5.1.2

* refactor: code review addressed by Zabuzard

* minimumReactions-5, star symbol instead of encoding

* requests changes by zabuzard except for moving getBoardChannel down and markMessageAsProcessed

* Following JavaDocs guidelines of making the first letter capital

* code refactoring

* refactor: use correct method for reactionsCount

It turns out that for each event fired, every *single* damn time,
messageReaction.hasCount() would always return false. No matter what.
Terrible documentation from JDA's side. As a result, because of the
ternary operator:

    messageReaction.hasCount() ? messageReaction.getCount() + 1 : 1

the result of `reactionsCount` would always end up holding the value of
one.

In the following changes, we use `messageReaction.retrieveUsers()` to
get a list of the people reacted, get a `Stream<User>` from that and get
its count. Much more reliable this way and it also happens to be more
readable.

Signed-off-by: Chris Sdogkos <work@chris-sdogkos.com>
Co-authored-by: Chris Sdogkos <work@chris-sdogkos.com>
Co-authored-by: Surya Tejess <74978874+suryatejess@users.noreply.github.com>

* doc(QuoteBoardForwarder.java): improve JavaDoc

Since 1ade40902b4 (refactor: code review addressed by Zabuzard,
2025-06-28) primarily contains a generaly vague JavaDoc describing what
the `QuoteBoardForwarder.java` class is doing, a more descriptive one
replaces it.

Signed-off-by: Chris Sdogkos <work@chris-sdogkos.com>

* refactor: code review addressed by zabuzard

* rename coolMessagesConfig to quoteMessagesConfig

* removed backticks for QuoteBoardForwarder and added a qualifier statement for QuoteBoardForwarder

* param check for reactionEmoji

* straight quotes instead of smart quotes

* rename isCoolEmoji to isTriggerEmoji

* early return when reactionsCount < config.minimumReactions()

* early return for isCoolEmoji

* fix: more renaming to quoteMessageConfig

Due to some hastiness in resolving the recent merge conflicts, some
parts with "coolMessagesConfig" were not renamed to
"quoteMessagesConfig".  Take care of that.

Signed-off-by: Chris Sdogkos <work@chris-sdogkos.com>

* fixes a single compilation error: "getCoolMessageConfig" is an old name

* applies FirasRG first review

Comments:
1. improved settings
2. using meaningful names
3. validations
4. some debug logs

* [smallFix] FirasRG first review: replace var with explicit type

---------

Signed-off-by: Chris Sdogkos <work@chris-sdogkos.com>
Co-authored-by: Surya Tejess <suryatejessk@gmail.com>
Co-authored-by: Surya Tejess <74978874+suryatejess@users.noreply.github.com>
Co-authored-by: Firas Regaieg <firasregayeg1220@yahoo.fr>